#!/usr/bin/env perl

use strict;
use warnings;
use lib qw/lib/;

use App::perlenv;
use Data::Printer;

unless (caller) {
    my $app = App::perlenv->new;
    $app->parse_cli_opts(@ARGV);
    p $app;
    #$app->doit or exit(1);
}
